### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by susheelbhanu** [Merlinaphist/ANNA16#1]
Hi, 

Thanks for providing the link to the Google colab notebook for `ANNA16`. Would you happen to have a standalone version of the tool for those clusters which have restricted internet access?

Thanks,
Susheel

**Comment by Merlinaphist** [comment]
Hi, currently we do not have a standalone version, but we could work to develop it. By standalone, do you mean a Python script that can be run on Command Line?
like: `./run_anna16.py -i input.fasta -o pred.csv`?

**Comment by susheelbhanu** [comment]
Yes, exactly. Thank you!

**Comment by Merlinaphist** [comment]
The command line app has been uploaded. Please see README.md.

**Comment by susheelbhanu** [comment]
Thank you - that works perfectly. I created a conda-env using the attached yaml file, should it be of any interest. 

Cheers,
Susheel 
[anna16.yaml.txt](https://github.com/Merlinaphist/ANNA16/files/14508129/anna16.yaml.txt)
