### ISSUE TITLE
1492R primer sequence in the README

### ISSUE THREAD

**Issue by masikol** [Merlinaphist/ANNA16#2]
Hi,

In the [README table](https://github.com/Merlinaphist/ANNA16?tab=readme-ov-file#data-preprocessing), primer 1492R has sequence `TAC GGY TAC CTT GTT ACG ACT`. However, this primer commonly has one more `T` base at the 3′ end: `TAC GGY TAC CTT GTT ACG ACT T`.
The question is whether it is a typo in the table, or the model has been trained using sequences trimmed with the 1492R sequence lacking this 3′-end `T`?

Thanks,
Maksim

**Comment by Merlinaphist** [comment]
Hi Maksim,
Thanks for pointing it out. After checking, we did use the 1492R sequence lacking this 3′-end `T`. We apologize for this confusion!
However, this probably does not influence the results of our paper.  In our training and testing, we did not trim the primers off but only used them to determine the range of the 16S genes. So, the results should be the same with or without the `T`. We trained [the additional version of model weights on primer-off sequences](https://github.com/Merlinaphist/ANNA16/tree/main/model_files/trimmed) only after the algorithm comparison was done. 
If you like it, we can re-train the primer-off version. Please just wait a few days. If your need is urgent, one easy workaround is to simply add a `T` after the V7 regions. 
Best,
Jiazheng

**Comment by masikol** [comment]
Thanks for making it clear!

> If you like it, we can re-train the primer-off version.

Oh, this would be great.

Thank you!

**Comment by Merlinaphist** [comment]
Hi masikol,

The new fixed version has been released. Sorry for the delay, I was too occupied by my Master's thesis.

**Comment by masikol** [comment]
Hi, Merlinaphist!

Nothing to apologize for :)
Thank you!
